[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.8    unsupported  02:03:36Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
postgresql                14.11    active      3  postgresql                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  151  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
postgresql/0*                active    idle   0        10.185.157.11   5432/tcp  
postgresql/1                 active    idle   1        10.185.157.76   5432/tcp  
postgresql/2                 active    idle   2        10.185.157.246  5432/tcp  Primary
self-signed-certificates/0*  active    idle   3        10.185.157.38             

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.185.157.11   juju-4a8d7c-0  ubuntu@22.04      Running
1        started  10.185.157.76   juju-4a8d7c-1  ubuntu@22.04      Running
2        started  10.185.157.246  juju-4a8d7c-2  ubuntu@22.04      Running
3        started  10.185.157.38   juju-4a8d7c-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-3: 01:40:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:40:38 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:40:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:40:38 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:40:38 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:40:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:40:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:40:39 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:40:39 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:40:39 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:40:39 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:40:40 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:40:40 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:40:40 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:40:40 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-1: 01:40:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 02:02:19 ERROR unit.postgresql/1.juju-log restart:1: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1533, in _restart
    assert False
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1530, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop=stop_after_delay(300)):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/tenacity/__init__.py", line 437, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/tenacity/__init__.py", line 370, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f10b094dc30 state=finished raised AssertionError>]
unit-postgresql-0: 02:02:38 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: connection to server at "10.185.157.246", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...