[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:548 starting continuous writes to the database
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:551 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:555 scaling out the first cluster
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: Primary
  postgresql/1 [idle] active: 
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [executing] maintenance: installing PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] active: Primary
  postgresql/1 [executing] active: 
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/1 [idle] active: 
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/1 [executing] active: 
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/1 [executing] active: 
  postgresql/3 [executing] waiting: awaiting for member to start
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: 
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: Primary
  postgresql/1 [idle] active: 
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: Primary
  postgresql/1 [idle] active: 
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:559 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:562 scaling out the second cluster
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/2 [idle] active: Standby
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/3 [executing] maintenance: installing PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/2 [executing] active: Standby
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/2 [executing] active: Standby
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/2 [idle] active: Standby
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/2 [idle] active: Standby
  postgresql/3 [executing] waiting: awaiting for member to start
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/2 [idle] active: Standby
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/2 [executing] active: Standby
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/2 [idle] active: Standby
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/2 [idle] active: Standby
  postgresql/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:568 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:571 scaling in the first cluster
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql (waiting for exactly 2 units, current : 3)
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql (waiting for exactly 2 units, current : 3)
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:86 Destroying second model
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.5    unsupported  02:37:31Z

App                  Version  Status  Scale  Charm                Channel      Rev  Exposed  Message
data-integrator               active      1  data-integrator      latest/edge   41  no       
postgresql           14.12    active      2  postgresql                          0  no       Primary
postgresql-test-app           active      1  postgresql-test-app  latest/edge  225  no       received database credentials of the first database

Unit                    Workload  Agent      Machine  Public address  Ports     Message
data-integrator/0*      active    idle       3        10.169.55.230             
postgresql-test-app/0*  active    executing  4        10.169.55.249             received database credentials of the first database
postgresql/1*           active    executing  1        10.169.55.91    5432/tcp  Primary
postgresql/3            active    executing  5        10.169.55.158   5432/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
1        started  10.169.55.91   juju-e0c91e-1  ubuntu@22.04      Running
3        started  10.169.55.230  juju-e0c91e-3  ubuntu@22.04      Running
4        started  10.169.55.249  juju-e0c91e-4  ubuntu@22.04      Running
5        started  10.169.55.158  juju-e0c91e-5  ubuntu@22.04      Running

Offer              Application  Charm       Rev  Connected  Endpoint           Interface         Role
replication        postgresql   postgresql  0    0/0        replication        postgresql_async  requirer
replication-offer  postgresql   postgresql  0    1/1        replication-offer  postgresql_async  provider

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-0: 01:36:58 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:36:58 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:37:01 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:37:09 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:37:10 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:37:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:37:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:37:13 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:37:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:37:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:37:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:37:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:38:14 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:38:14 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:38:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-test-app-0: 02:06:18 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "09cc7869-020f-42ab-8c53-8c203ee0c91e:r#6#postgresql": settings 09cc7869-020f-42ab-8c53-8c203ee0c91e:r#6#postgresql not found (not found)
unit-postgresql-0: 02:06:20 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "09cc7869-020f-42ab-8c53-8c203ee0c91e:r#6#postgresql-test-app": settings 09cc7869-020f-42ab-8c53-8c203ee0c91e:r#6#postgresql-test-app not found (not found)
unit-postgresql-2: 02:07:19 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "09cc7869-020f-42ab-8c53-8c203ee0c91e:r#7#remote-72c1865ff3f74ee78236dd1efcbfd7e5": settings 09cc7869-020f-42ab-8c53-8c203ee0c91e:r#7#remote-72c1865ff3f74ee78236dd1efcbfd7e5 not found (not found)
machine-5: 02:23:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:23:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-3: 02:23:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 02:37:03 ERROR unit.postgresql/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-1/secret-info-get', '--label', 'database.4.user.secret', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 3563, in _run_for_secret
    return self._run(*args, return_output=return_output, use_json=use_json)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR secret "database.4.user.secret" not found


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1859, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 724, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1350, in _on_update_status
    self._update_relation_endpoints()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 724, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1732, in _update_relation_endpoints
    self.postgresql_client_relation.update_endpoints()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 724, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/relations/postgresql_provider.py", line 215, in update_endpoints
    self.database_provides.set_uris(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2842, in set_uris
    self.update_relation_data(relation_id, {"uris": uris})
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 492, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1403, in update_relation_data
    return self._update_relation_data(relation, data)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1624, in _update_relation_data
    _, normal_fields = self._process_secret_fields(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1186, in _process_secret_fields
    if group_result := operation(relation, group, secret_fields, *args, **kwargs):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1527, in _add_or_update_relation_secrets
    return self._update_relation_secret(relation, group, secret_fields, data)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 504, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1512, in _update_relation_secret
    secret.set_content(full_content)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 769, in set_content
    self.meta.set_content(content)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 1437, in set_content
    self._id = self.get_info().id
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 1418, in get_info
    return self._backend.secret_info_get(id=self.id, label=self.label)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 3577, in secret_info_get
    result = self._run_for_secret('secret-info-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/model.py", line 3566, in _run_for_secret
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError
unit-postgresql-1: 02:37:04 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-test-app-0: 02:37:19 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 301, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.169.55.107", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:37:19 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 538, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 310, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...